name = "rajeev-persaud-portfolio"
compatibility_date = "2024-01-01"

pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "rajeev-persaud-portfolio"
routes = [
  { pattern = "*", zone_name = "rajeevpersaud.com" }
]

[env.preview]
name = "rajeev-persaud-portfolio-preview"
